### ISSUE TITLE
Re check

### ISSUE THREAD

**Issue by marzia2936** [marzia2936/C-Programming-Code#3]
// Check whether an integer is odd or even

#include <stdio.h>
int main() {
    int number;
    printf("Enter an integer: ");
    scanf("%d", &number);

    // True if the remainder is 0
    if  (number%2 == 0) {
        printf("%d is an even integer.",number);
    }
    else {
        printf("%d is an odd integer.",number);
    }

    return 0;
}

**Comment by tahsin469** [comment]
code is ok

**Comment by marzia2936** [comment]
Thank you
